#!/bin/bash

# Log output:
# 
# * 238b2a       (10 days)    <Tim Uruski>     did some work
#
# Stolen from Gary Bernhardt
# https://github.com/garybernhardt/dotfiles/blob/master/.githelpers
# https://www.destroyallsoftware.com/screencasts/catalog/pretty-git-logs

HASH="%C(yellow)%h%C(reset)"
RELATIVE_TIME="%C(green)(%ar)%C(reset)"
AUTHOR="%C(bold blue)<%an>%C(reset)"
REFS="%C(red)%d%C(reset)"
SUBJECT="%s"

FORMAT="$HASH}$RELATIVE_TIME}$AUTHOR}$REFS $SUBJECT"

show_git_head() {
  pretty_git_log -1
  git show -p --pretty="tformat:"
}

pretty_git_log() {
  git log --graph --abbrev-commit --date=relative --pretty="tformat:${FORMAT}" $* | 
      # Replace (2 years ago) with (2 years)
      sed -Ee 's/(^[^<]*) ago)/\1)/' |
      # Replace (2 years, 5 months) wiht (2 years)
      sed -Ee 's/(^[^>]*), [[:digit:]]+ .*months?)/\1)/' |
      # Columnate based on } delimiter
      column -s '}' -t |
      # Page with colors, only when necessary, leave it on the screen
      less -FSXR
}

deploy_git_log() {
  ref=${1:-'master'}

  date +"%d %b %Y"
  git log --pretty="tformat:  - %s [%an]" origin/$ref..$ref | 
  sed -Ee 's/\[([a-zA-Z]).+ ([a-zA-Z]).+\]$/[\1\2]/'
}

current_branch() {
  # The --short was introduced in 1.7.9, this might be more portable.
  # git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||'
  git symbolic-ref --short --quiet HEAD
}

ffwd() {
  ref=${1:-`current_branch`}
  git merge --ff-only origin/$ref
}

# Assumes input date is formatted as YYYY-MM-DD,
# passes additional arguments to git-log.
sred_log() {
  date_format='%Y-%m-%d'
  sred_date="${1:-$(date +"$date_format")}"
  shift

  until=$(date -v "+1d" -jf "$date_format" "${sred_date}")
  since=$(date -v "-6d" -jf "$date_format" "${sred_date}")
  author=$(git config --get user.email)

  git log --reverse --author "${author}" --since "${since}" --until "${until}" ${@}
}

git_wip() {
  git add --update
  git commit --no-verify --message "WIP $1"
}
