#!/usr/bin/env ruby -r ./dotfiles

# TODO Automatically run install at_exit
Dotfiles.install do
  dotfile "ackrc"
  dotfile "bash_profile"
  dotfile "bashrc"
  symlink "bin/b"
  symlink "bin/edit"
  symlink! "bin/git-*"
  symlink "bin/git_prompt.rb"
  symlink "bin/pjson"
  symlink "bin/x"
  dotfile "direnvrc"
  dotfile "gitconfig"
  dotfile "githelpers"
  dotfile "gitignore_global"
  dotfile "gvimrc"
  dotfile "inputrc"
  dotfile "irbrc"
  dotfile "nvim", to: "config/nvim"
  dotfile "psqlrc"
  dotfile "railsrc"
  dotfile "screenrc"
  dotfile "tmux.conf"
  dotfile "vim"
  dotfile "zshenv"
  dotfile "zsh", to: "config/zsh"
end
