#!/usr/bin/env ruby

require_relative "./dotfiles"

Dotfiles.install do
  symlink "ackrc"
  symlink "bash_profile"
  symlink "bashrc"
  symlink "bin/b", dot_prefix: false
  symlink "bin/edit", dot_prefix: false
  symlink "bin/git-*", dot_prefix: false
  symlink "bin/git_prompt.rb", dot_prefix: false
  symlink "bin/pjson", dot_prefix: false
  symlink "bin/x", dot_prefix: false
  symlink "direnvrc"
  symlink "gitconfig"
  symlink "githelpers"
  symlink "gitignore_global"
  symlink "gvimrc"
  symlink "inputrc"
  symlink "irbrc"
  symlink "psqlrc"
  symlink "railsrc"
  symlink "screenrc"
  symlink "tmux.conf"
  symlink "zlogin"
  symlink "zshrc"
end
