#!/usr/bin/env ruby

require_relative "./dotfiles"

Dotfiles.install(dest: "tmp", dry_run: false) do
  symlink "ackrc"
  symlink "bash_profile"
  symlink "bashrc"
  # How many files in bin/* are even necessary?
  symlink "bin/git-*", dot_prefix: false
  symlink "direnvrc"
  symlink "gitconfig"
  symlink "githelpers"
  symlink "gitignore_global"
  symlink "gvimrc"
  symlink "inputrc"
  symlink "irbrc"
  symlink "new-install"
  symlink "psqlrc"
  symlink "railsrc"
  symlink "screenrc"
  symlink "tmux.conf"
  symlink "zlogin"
  symlink "zshrc"
end
