#!/bin/bash

# rsync work files to an external volume
# https://serverfault.com/questions/25329/using-rsync-to-backup-to-an-external-drive#25398

SOURCE=(
  "$HOME/.ssh"
  "$HOME/.dotfiles"
  "$HOME/workspace/clio"
)

# TODO: Abort if not present
ORIGIN="${1:-/Volumes/Backup}"

# -gloptrunc
OPTS=(
  --group
  --links
  --owner
  --perms
  --times
  --recursive
  --update
  --dry-run
  --checksum
  --verbose
)

rsync ${OPTS[@]} ${SOURCE[@]} "$DEST"
