# Load modules
autoload -U compinit && compinit
autoload -U colors && colors

# Options
setopt prompt_subst
setopt emacs
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE

# Setup chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby 3.1.1

# fzf
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

function fcd() { cd *$1* }

# Workspace shortcut and completion
# function ws() { cd ~/workspace/$1; }
function _ws() { _files -W $HOME/workspace -/; }
compdef _ws ws


# Z jump around https://github.com/rupa/z
[[ -f `brew --prefix`/etc/profile.d/z.sh ]] && . `brew --prefix`/etc/profile.d/z.sh

# Direnv https://direnv.net
eval "$(direnv hook zsh)"

# Iterm2 integration
if [[ $ITERM_SESSION_ID ]]; then
  # source ~/.zsh/iterm2.sh
  source "$ZDOTDIR/iterm2.sh"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Plugins
source "$ZDOTDIR/aliases.sh"
source "$ZDOTDIR/functions.sh"

# TODO Break this apart.
for plugin in $ZDOTDIR/plugins/*.sh; do
  source "$plugin"
done
