# Load modules
autoload -U compinit && compinit
autoload -U colors && colors

# Options
setopt prompt_subst
setopt emacs
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE

# Setup chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
# chruby 3.2.2

# Completions
fpath=($ZDOTDIR $fpath)
autoload -Uz compinit
# Speed up compinit
# https://registerspill.thorstenball.com/p/how-fast-is-your-shell
# https://github.com/mrnugget/dotfiles/commit/89b6b8213d4dc15e5cb7612792a6e33de1d963c7
if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
  compinit
else
  compinit -C
fi

# fzf
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

# Workspace shortcut and completion
# function ws() { cd ~/workspace/$1; }
# function _ws() { _files -W $HOME/workspace -/; }
# compdef _ws ws


# Z jump around https://github.com/rupa/z
# brew --prefix /usr/local
[[ -e /usr/local/etc/profile.d/z.sh ]] && . /usr/local/etc/profile.d/z.sh

# Direnv https://direnv.net
eval "$(direnv hook zsh)"

# Iterm2 integration
test $ITERM_SESSION_ID && source "$ZDOTDIR/iterm2.sh"
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Plugins
source "$ZDOTDIR/aliases.sh"
source "$ZDOTDIR/functions.sh"

# TODO Break this apart.
for plugin in $ZDOTDIR/plugins/*.sh; do
  source "$plugin"
done
